### ISSUE TITLE
Doc: instructions need to be updated for istio 0.2 under istio-system namespace

### ISSUE THREAD

**Issue by saturnism** [istio/issues#65]
**Is this a BUG or FEATURE REQUEST?:** BUG

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics): Yes

**Bug:** Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
Version: 0.2.4
GitRevision: 9c7c291eab0a522f8033decd0f5b031f5ed0e126
GitBranch: master
User: root@822a7ac3ca86
GolangVersion: go1.8.3

kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", 
Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T08:56:23Z", GoVersion:"go1.8.3", 
Compiler:"gc", Platform:"linux/amd64"}
```
**Is Istio Auth enabled or not ?** No

**What happened**: Grafana instruction is oudated. It needs to be scoped to the namespace. E.g., 
```
kubectl port-forward --namespace=istio-system $(kubectl get pod --namespace=istio-system -l app=grafana -o jsonpath='{.items[0].metadata.name}') 3000:3000
```
Same thing w/ Service Graph

In https://istio.io/docs/tasks/telemetry/distributed-tracing.html, Zipkin command also needs to be updated. It's currently:
`kubectl port-forward $(kubectl get pod -l app=zipkin -o jsonpath='{.items[0].metadata.name}') 9411:9411 &`

**Comment by lgfa29** [comment]
@saturnism the same needs to be done in the **Verifying the ServiceGraph service**:

```
kubectl port-forward $(kubectl get pod -l app=servicegraph -o jsonpath='{.items[0].metadata.name}') 8088:8088 &
```

**Comment by linsun** [comment]
Just checked:  This is fixed per latest doc:  https://istio.io/docs/setup/kubernetes/quick-start.html  please reopen if I'm wrong.

Many thanks for reporting this. :)

**Comment by lgfa29** [comment]
@linsun the link that you posted is still wrong. The port forward command has two `kubeclt` calls and they both need to set the name space. Currently only the outermost command has `-n istio-system`.

**Comment by saturnism** [comment]
+1, pls reopen. there are more than one place that the doc has this issue too. i'd suggest keep open until all issues have been tried/tested/validated before closing.

E.g., https://istio.io/docs/tasks/telemetry/distributed-tracing.html also has issue w/ zipkin

**Comment by ZackButcher** [comment]
Reopening to track all of the places we need to update this.

**Comment by galo** [comment]
On https://istio.io/docs/tasks/security/istio-auth.html

```
 istio-0.2.4 $ kubectl get deploy -l istio=istio-ca -n istio-system
```

**Comment by linsun** [comment]
It is fine to keep this global for all namespace issues.  @lgfa29 the link i saw has both of the two port-forward command with -n istio-namespace.

**Comment by lgfa29** [comment]
@linsun Both Graphana and ServiceGraph commands have the `-n` param, but my point is that each of them has two `kubectl` calls, and they both need `-n`. So they should be

```
  kubectl port-forward -n istio-system $(
         kubectl get pod -n istio-system -l app=grafana -o jsonpath='{.items[0].metadata.name}'
) 3000:3000 &
```

**Comment by linsun** [comment]
Thanks for the clarification, now I see why you would want to set the namespace context now.
